name: Build and test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  catalina-swift5_3:
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2
      - name: Build on macOS 10.15 with Swift 5.3
        run: |
          sudo xcode-select --switch /Applications/Xcode_12.3.app/Contents/Developer
          swift build -c release
          swift test -c release --enable-test-discovery
          brew bundle
          cd TestApp && ../.build/release/carton test
          ../.build/release/carton test --environment defaultBrowser
          ../.build/release/carton bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  bigsur-swift5_3:
    runs-on: macos-11.0

    steps:
      - uses: actions/checkout@v2
      - name: Build on macOS 11.0 with Swift 5.3
        run: |
          sudo xcode-select --switch /Applications/Xcode_12.3.app/Contents/Developer
          swift build -c release
          swift test -c release --enable-test-discovery
          brew bundle
          cd TestApp && ../.build/release/carton test
          ../.build/release/carton test --environment defaultBrowser
          ../.build/release/carton bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ubuntu18_04-swift5_3:
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Build on Ubuntu 18.04 with Swift 5.3
        run: |
          sudo ./install_ubuntu_deps.sh
          swift test -c release --enable-test-discovery
          cd TestApp && ../.build/release/carton test
          ../.build/release/carton bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  ubuntu20_04-swift5_3:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - name: Build on Ubuntu 20.04 with Swift 5.3
        run: |
          sudo ./install_ubuntu_deps.sh
          swift test -c release --enable-test-discovery
          cd TestApp && ../.build/release/carton test
          ../.build/release/carton bundle
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker_image:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build a Docker image on Ubuntu 20.04
        run: docker build . -t gchr.io/swiftwasm/swiftwasm-action:latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
